"use client";
import { useEffect,useMemo,useState } from "react";
import { CalendarDays, Check, Clock3, Plus, Trash2 } from "lucide-react";
import AuthPanel from "../auth-panel";
import { createClient } from "@/lib/supabase/client";
type Task={id:string;title:string;scheduled_date:string;start_time:string;end_time:string;priority:string;category:string;notes?:string;done:boolean};
const today=new Date().toISOString().slice(0,10);
export default function Planner(){const supabase=createClient();const [date,setDate]=useState(today);const [tasks,setTasks]=useState<Task[]>([]);const [error,setError]=useState("");const [form,setForm]=useState({title:"",start_time:"07:00",end_time:"08:00",priority:"medium",category:"field",notes:""});
 const load=async()=>{const {data,error}=await supabase.from("tasks").select("*").eq("scheduled_date",date).order("start_time");setTasks((data||[]) as Task[]);setError(error?.message||"")};useEffect(()=>{load()},[date]);useEffect(()=>{const channel=supabase.channel("tasks-live").on("postgres_changes",{event:"*",schema:"public",table:"tasks"},load).subscribe();return()=>{supabase.removeChannel(channel)}},[date]);
 const add=async(e:React.FormEvent)=>{e.preventDefault();const {error}=await supabase.from("tasks").insert({...form,scheduled_date:date,due_date:date});if(error)setError(error.message);else{setForm({...form,title:"",notes:""});load()}};const toggle=async(t:Task)=>{await supabase.from("tasks").update({done:!t.done}).eq("id",t.id);load()};const remove=async(id:string)=>{if(confirm("Remove this plan item?")){await supabase.from("tasks").delete().eq("id",id);load()}};
 const hours=useMemo(()=>tasks.reduce((n,t)=>n+(new Date(`2000-01-01T${t.end_time}`).getTime()-new Date(`2000-01-01T${t.start_time}`).getTime())/36e5,0),[tasks]);return <div className="contacts-shell"><header className="contacts-top"><a href="/" className="brand"><div className="brand-mark">M<span>28</span></div><div><strong>Mission 2028</strong><small>Daily operations</small></div></a><a href="/contacts">Contacts</a></header><main className="contacts-main"><AuthPanel/><section className="contacts-heading"><div><p className="eyebrow"><CalendarDays size={14}/> Execution planner</p><h1>Design a focused 10–12 hour day</h1><p>Coordinate meetings, village visits, programs, finance, follow-ups, and personal routines.</p></div><div className="day-total"><b>{hours.toFixed(1)}h</b><span>planned</span></div></section><div className="planner-grid"><form className="plan-form" onSubmit={add}><h2>Add time block</h2><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Action<input required placeholder="Meet youth group in Bejjur" value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><div><label>Start<input type="time" value={form.start_time} onChange={e=>setForm({...form,start_time:e.target.value})}/></label><label>End<input type="time" value={form.end_time} onChange={e=>setForm({...form,end_time:e.target.value})}/></label></div><div><label>Category<select value={form.category} onChange={e=>setForm({...form,category:e.target.value})}>{["routine","field","meeting","program","finance","follow-up","travel"].map(x=><option key={x}>{x}</option>)}</select></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>low</option><option>medium</option><option>high</option></select></label></div><label>Coordination notes<textarea placeholder="Village, people, desired outcome, preparation…" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/></label><button className="primary"><Plus size={16}/> Add to day</button>{error&&<small className="form-error">{error} · Sign in and ensure migration 0003 is applied.</small>}</form><section className="timeline"><div className="timeline-head"><h2>{date}</h2><span>{tasks.filter(t=>t.done).length}/{tasks.length} completed</span></div>{tasks.map(t=><article className={`time-block ${t.done?"done":""}`} key={t.id}><div className="time"><Clock3 size={14}/><b>{t.start_time?.slice(0,5)}</b><span>{t.end_time?.slice(0,5)}</span></div><div><small className={`priority ${t.priority}`}>{t.priority} · {t.category}</small><h3>{t.title}</h3>{t.notes&&<p>{t.notes}</p>}</div><button onClick={()=>toggle(t)}><Check/></button><button onClick={()=>remove(t.id)}><Trash2/></button></article>)}{!tasks.length&&!error&&<div className="empty">No live plan yet. Add the first time block.</div>}</section></div></main></div>}
